# Pull base image
FROM python:3.10

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code/

# Install dependencies 
# COPY ./app/requirements.txt /code/requirements.txt
COPY ./app /code
RUN cd /code && pip install --no-cache-dir --upgrade -r requirements.txt
# RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
